"""Install the existing launch runtime into Heroic's Flatpak data directory.

The game stays in Heroic's sandbox. Only PenguinBurner's configuration, shared
telemetry directory and daemon socket are exposed; no host-execution permission
or host Python installation is needed. Called only by an explicit settings write.
"""

from __future__ import annotations

import hashlib
import io
import json
from pathlib import Path
import shlex
import tempfile
import zipfile

from common.atomic_write import atomic_write_text
from integrations.launchers.host_process import run_on_host
from overlay.native_layer import (
    NATIVE_LAYER_LIBRARY,
    NATIVE_LAYER_LIBRARY_I386,
    NATIVE_LAYER_MANIFEST,
    NATIVE_LAYER_MANIFEST_I386,
    native_layer_dirs,
)
from overlay.shim_deploy import nvapi_shim_artifact

from .paths import HEROIC_FLATPAK_DIRNAME, heroic_config_root

APP_ID = "com.heroicgameslauncher.hgl"
# RuntimeSpec resolves saved profiles using these owners. Export source only:
# Python and its standard library belong to Heroic's runtime, not to the host.
RUNTIME_PACKAGES = (
    "auto_uv", "cli", "common", "curve_editors", "drivers", "integrations",
    "overlay", "profiles", "runtime", "stability", "ui",
)


def uses_flatpak(home: Path | None = None) -> bool:
    base = Path.home() if home is None else home
    return heroic_config_root(home) == base / HEROIC_FLATPAK_DIRNAME


def wrapper_path(home: Path | None = None) -> Path:
    base = Path.home() if home is None else home
    return base / ".var/app" / APP_ID / "data/penguin-burner/PENGUIN_BURNER"


def sandbox_command(command: str, home: Path | None = None) -> str:
    """Translate only the wrapper executable, preserving user wrapper rows."""
    words = shlex.split(command)
    return shlex.join([
        str(wrapper_path(home)) if word == "PENGUIN_BURNER" else word
        for word in words
    ])


def _runtime_archive(source: Path) -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for package in RUNTIME_PACKAGES:
            for path in sorted((source / package).rglob("*.py")):
                if "__pycache__" in path.parts:
                    continue
                entry = zipfile.ZipInfo(path.relative_to(source).as_posix())
                entry.compress_type = zipfile.ZIP_DEFLATED
                archive.writestr(entry, path.read_bytes())
    return buffer.getvalue()


def _payload(source: Path) -> dict[str, bytes]:
    layers = native_layer_dirs()
    if not layers:
        raise RuntimeError("The packaged PenguinBurner Vulkan layer is missing.")
    layer = layers[0]
    files = {"runtime.zip": _runtime_archive(source)}
    for name in (
        NATIVE_LAYER_LIBRARY, NATIVE_LAYER_MANIFEST,
        NATIVE_LAYER_LIBRARY_I386, NATIVE_LAYER_MANIFEST_I386,
    ):
        path = layer / name
        if path.is_file():
            files[f"native_layer/{name}"] = path.read_bytes()
    shim = nvapi_shim_artifact()
    if shim is None:
        raise RuntimeError("The packaged PenguinBurner NVAPI shim is missing.")
    files["nvapi_shim/nvapi64.dll"] = shim.read_bytes()
    return files


def _wrapper_text(payload: Path) -> str:
    return f'''#!/usr/bin/python3
# Generated by PenguinBurner for Flatpak Heroic.
import ctypes
import os
from pathlib import Path
import sys

payload = Path({str(payload)!r})
archive = str(payload / "runtime.zip")
sys.path.insert(0, archive)
os.environ["PENGUIN_BURNER_SESSION_HELPER_PYTHONPATH"] = archive
os.environ["PENGUIN_BURNER_NATIVE_LAYER_DIR"] = str(payload / "native_layer")
os.environ["PENGUIN_BURNER_NVAPI_SHIM_DIR"] = str(payload / "nvapi_shim")
if sys.argv[1:] == ["--check-integration"]:
    import runtime.runtime_spec
    from runtime.daemon_client import client_host_pid
    ctypes.CDLL(str(payload / "native_layer/{NATIVE_LAYER_LIBRARY}"))
    print("PenguinBurner Flatpak runtime ready; host PID", client_host_pid())
else:
    from overlay.launcher import main
    raise SystemExit(main())
'''


def ensure_integration(home: Path | None = None) -> None:
    """Prepare payload and grants, then probe inside a fresh Heroic sandbox.

    Existing Heroic processes need restarting to receive new filesystem grants.
    Flatpak merges these per-app grants with existing overrides.
    """
    base = Path.home() if home is None else home
    wrapper = wrapper_path(base)
    files = _payload(Path(__file__).resolve().parents[2])
    digest = hashlib.sha256()
    for name, content in sorted(files.items()):
        digest.update(name.encode() + b"\0" + content)
    payload = wrapper.parent / digest.hexdigest()[:24]
    if not payload.is_dir():
        wrapper.parent.mkdir(parents=True, exist_ok=True)
        # Retain old payloads: an already-running game's helpers may use them.
        with tempfile.TemporaryDirectory(dir=wrapper.parent, prefix="prepare-") as temporary:
            staging = Path(temporary) / "payload"
            for name, content in files.items():
                target = staging / name
                target.parent.mkdir(parents=True, exist_ok=True)
                if name.endswith(".json"):
                    manifest = json.loads(content)
                    library = Path(manifest["layer"]["library_path"]).name
                    manifest["layer"]["library_path"] = str(payload / "native_layer" / library)
                    content = (json.dumps(manifest, indent=2) + "\n").encode()
                target.write_bytes(content)
            staging.rename(payload)
    atomic_write_text(wrapper, _wrapper_text(payload), durable=True)
    wrapper.chmod(0o755)
    config = base / ".config/PenguinBurner"
    cache = base / ".cache/penguin-burner"
    config.mkdir(parents=True, exist_ok=True)
    cache.mkdir(parents=True, exist_ok=True)
    grants = [
        f"--filesystem={config}", f"--filesystem={cache}",
        "--filesystem=/run/penguin-burnerd.sock",
    ]
    result = run_on_host(
        ["flatpak", "override", "--user", *grants, APP_ID], capture=True,
    )
    if result is None or result.returncode:
        detail = "Flatpak unavailable" if result is None else result.stderr.strip()
        raise RuntimeError(f"Could not prepare Heroic Flatpak access: {detail}")
    result = run_on_host(
        ["flatpak", "run", f"--command={wrapper}", APP_ID, "--check-integration"],
        capture=True, timeout=20.0,
    )
    if result is None or result.returncode:
        detail = "sandbox probe timed out" if result is None else result.stderr.strip()
        raise RuntimeError(
            "Heroic Flatpak integration check failed. Update/restart the PenguinBurner "
            f"daemon and retry. {detail}"
        )
