from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import sys
import tempfile

from overlay.native_layer import NATIVE_LAYER_LIBRARY
from overlay.native_layer import NATIVE_LAYER_MANIFEST
from overlay.native_layer import native_layer_dirs


APP_ID = "io.github.jpietek.PenguinBurner"
MARKER = "Generated by PenguinBurner Flatpak wrapper installer"
VULKAN_LAYER_ENABLE_ENV = "PENGUIN_BURNER"
VULKAN_LAYER_DISABLE_ENV = "DISABLE_PENGUIN_BURNER_LATENCY_LAYER"
WRAPPERS = (
    "penguin-burner",
    "pburn",
    "penguin-burner-cli",
    "pburn-cli",
    "PENGUIN_BURNER",
)
# Command names shipped by older releases that are no longer installed.
# Uninstall and the silent Flatpak repair still sweep these so hosts that
# installed them under an earlier version are not left with orphaned
# wrappers pointing at removed sandbox entry points.
LEGACY_WRAPPERS = (
    "penguin-burner-ui",
    "pburn-ui",
)


def _default_bin_dir() -> Path:
    override = os.environ.get("PENGUIN_BURNER_FLATPAK_WRAPPER_BIN_DIR")
    if override:
        return Path(override).expanduser()
    return Path.home() / ".local" / "bin"


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Install host PATH wrappers for the PenguinBurner Flatpak. "
            "The wrappers forward to flatpak run --command=<name> "
            f"{APP_ID}."
        )
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="overwrite existing non-PenguinBurner wrapper files",
    )
    parser.add_argument(
        "--uninstall",
        action="store_true",
        help="remove wrappers previously created by this command",
    )
    parser.add_argument(
        "--bin-dir",
        type=Path,
        default=_default_bin_dir(),
        help="install/remove wrappers in DIR (default: ~/.local/bin)",
        metavar="DIR",
    )
    return parser


def _is_managed_wrapper(path: Path) -> bool:
    try:
        return path.is_file() and MARKER in path.read_text(
            encoding="utf-8", errors="replace"
        )
    except OSError:
        return False


def _is_native_steam_wrapper(path: Path) -> bool:
    try:
        return (
            path.is_file()
            and os.access(path, os.X_OK)
            and "from overlay.launcher import main"
            in path.read_text(encoding="utf-8", errors="replace")
        )
    except OSError:
        return False


def running_in_flatpak(
    *,
    environ: dict[str, str] | None = None,
    flatpak_info_path: Path = Path("/.flatpak-info"),
) -> bool:
    env = os.environ if environ is None else environ
    return bool(env.get("FLATPAK_ID", "").strip()) or flatpak_info_path.is_file()


def _write_wrapper_atomic(target: Path, text: str) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary_name = tempfile.mkstemp(
        dir=target.parent,
        prefix=f".{target.name}.",
        suffix=".tmp",
        text=True,
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
        temporary.chmod(0o755)
        temporary.replace(target)
    finally:
        temporary.unlink(missing_ok=True)


def ensure_steam_wrapper(
    bin_dir: Path | str | None = None,
    *,
    only_if_flatpak: bool = True,
) -> Path | None:
    """Install or refresh the host Steam wrapper required by launch options.

    Flatpak cannot run a host post-install hook, so the complete integration
    repair calls this low-level helper when needed. Native Python installs get
    the same command from the ``PENGUIN_BURNER`` console-script entry point and
    therefore do not need a generated host wrapper.
    """
    if only_if_flatpak and not running_in_flatpak():
        return None
    root = _default_bin_dir() if bin_dir is None else Path(bin_dir).expanduser()
    target = root / "PENGUIN_BURNER"
    if target.exists() and not _is_managed_wrapper(target):
        raise RuntimeError(
            f"refusing to overwrite existing command: {target} "
            "(remove it or run penguin-burner-install-wrappers --force)"
        )
    expected = _wrapper_text("PENGUIN_BURNER")
    try:
        current = target.read_text(encoding="utf-8")
    except FileNotFoundError:
        current = ""
    if current != expected or not os.access(target, os.X_OK):
        _write_wrapper_atomic(target, expected)
    return target


def ensure_flatpak_wrappers(
    bin_dir: Path | str | None = None,
) -> tuple[Path, ...]:
    """Silently repair every generated Flatpak host command.

    Existing non-managed commands are left untouched so a native/PyPI install
    is never overwritten by merely launching the Flatpak. A clean Flatpak-only
    installation receives the complete command set on first GUI start.
    """
    if not running_in_flatpak():
        return ()
    root = _default_bin_dir() if bin_dir is None else Path(bin_dir).expanduser()
    repaired: list[Path] = []
    for command_name in WRAPPERS:
        target = root / command_name
        if target.exists() and not _is_managed_wrapper(target):
            continue
        expected = _wrapper_text(command_name)
        try:
            current = target.read_text(encoding="utf-8")
        except FileNotFoundError:
            current = ""
        if current != expected or not os.access(target, os.X_OK):
            _write_wrapper_atomic(target, expected)
        repaired.append(target)
    _remove_legacy_wrappers(root)
    return tuple(repaired)


def _remove_legacy_wrappers(bin_dir: Path) -> list[Path]:
    """Delete generated wrappers for command names this version no longer
    ships. Their sandbox entry points are gone, so a stale wrapper would fail
    at ``flatpak run --command=...``. Only marker-managed files are touched."""
    removed: list[Path] = []
    for command_name in LEGACY_WRAPPERS:
        target = bin_dir / command_name
        if _is_managed_wrapper(target):
            target.unlink()
            removed.append(target)
    return removed


def _default_vulkan_manifest_path(home: Path | str | None = None) -> Path:
    home = Path.home() if home is None else Path(home).expanduser()
    return (
        home
        / ".local"
        / "share"
        / "vulkan"
        / "implicit_layer.d"
        / NATIVE_LAYER_MANIFEST
    )


def _stabilize_flatpak_deploy_path(path: Path) -> Path:
    """Rewrite a commit-specific flatpak deploy path to the stable ``active``
    symlink.

    A flatpak deploy path is ``.../<branch>/<commit-hash>/files/...``; the
    Vulkan layer manifest must NOT bake in ``<commit-hash>``, because a
    ``flatpak update`` swaps the active deploy to a new commit and prunes the
    old one — leaving the manifest's library_path dangling and every wrapped
    Vulkan game failing to load the layer. The sibling ``<branch>/active``
    symlink always points at the current deploy, so pinning to it survives
    updates with no wrapper reinstall. Falls back to the original path when the
    ``active`` form does not resolve (e.g. a non-flatpak layout)."""
    parts = list(path.parts)
    try:
        files_index = parts.index("files")
    except ValueError:
        return path
    commit_index = files_index - 1
    if commit_index <= 0:
        return path
    commit = parts[commit_index]
    is_commit = len(commit) == 64 and all(c in "0123456789abcdef" for c in commit)
    if not is_commit:
        return path
    # Structural rewrite only: flatpak always maintains the <branch>/active
    # symlink next to a deploy commit, and the installer runs inside the
    # sandbox where the host active/ path is not visible to stat — so an
    # existence check here would wrongly fall back to the commit path.
    return Path(*parts[:commit_index], "active", *parts[files_index:])


def _host_vulkan_manifest_text(
    native_layer_dir: Path,
    *,
    source_layer_dir: Path | None = None,
) -> str:
    source_layer_dir = native_layer_dir if source_layer_dir is None else source_layer_dir
    manifest = source_layer_dir / NATIVE_LAYER_MANIFEST
    data = json.loads(manifest.read_text(encoding="utf-8"))
    layer = dict(data["layer"])
    layer["library_path"] = str(
        _stabilize_flatpak_deploy_path(native_layer_dir) / NATIVE_LAYER_LIBRARY
    )
    layer["enable_environment"] = {VULKAN_LAYER_ENABLE_ENV: "1"}
    layer["disable_environment"] = {VULKAN_LAYER_DISABLE_ENV: ""}
    data["layer"] = layer
    return json.dumps(data, indent=2) + "\n"


def _flatpak_app_path(flatpak_info_path: Path = Path("/.flatpak-info")) -> Path | None:
    try:
        lines = flatpak_info_path.read_text(
            encoding="utf-8", errors="replace"
        ).splitlines()
    except OSError:
        return None
    for line in lines:
        if line.startswith("app-path="):
            value = line.partition("=")[2].strip()
            if value:
                return Path(value)
    return None


def _native_layer_dirs_from_app_files(app_files: Path) -> list[Path]:
    candidates = [
        path / "overlay" / "native_layer"
        for path in (app_files / "lib").glob("python*/site-packages")
    ]
    return [
        path
        for path in candidates
        if (path / NATIVE_LAYER_MANIFEST).is_file()
        and (path / NATIVE_LAYER_LIBRARY).is_file()
    ]


def _native_layer_dirs_for_host_manifest(
    flatpak_info_path: Path = Path("/.flatpak-info"),
) -> list[tuple[Path, Path]]:
    candidates: list[tuple[Path, Path]] = []
    source_dirs = native_layer_dirs()
    flatpak_app_path = _flatpak_app_path(flatpak_info_path)
    if flatpak_app_path is not None:
        visible_host_dirs = _native_layer_dirs_from_app_files(flatpak_app_path)
        candidates.extend((path, path) for path in visible_host_dirs)
        for source_dir in source_dirs:
            try:
                relative = source_dir.resolve().relative_to(Path("/app"))
            except ValueError:
                continue
            candidates.append((flatpak_app_path / relative, source_dir))
    candidates.extend((path, path) for path in source_dirs)

    unique: list[tuple[Path, Path]] = []
    seen: set[Path] = set()
    for host_path, source_path in candidates:
        if host_path not in seen:
            unique.append((host_path, source_path))
            seen.add(host_path)
    return unique


def install_vulkan_layer_manifest(
    *,
    home: Path | str | None = None,
    layer_dirs: list[Path] | tuple[Path, ...] | None = None,
    flatpak_info_path: Path = Path("/.flatpak-info"),
) -> Path | None:
    candidates: list[tuple[Path, Path]] = list(
        _native_layer_dirs_for_host_manifest(flatpak_info_path)
        if layer_dirs is None
        else [(path, path) for path in layer_dirs]
    )
    if not candidates:
        return None
    host_layer_dir, source_layer_dir = candidates[0]
    target = _default_vulkan_manifest_path(home)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        _host_vulkan_manifest_text(
            host_layer_dir,
            source_layer_dir=source_layer_dir,
        ),
        encoding="utf-8",
    )
    target.chmod(0o644)
    return target


def ensure_host_integration() -> Path | None:
    """Repair and verify every host-facing Flatpak launcher component.

    The shim is deployed into each wine prefix by ``overlay.launcher`` at
    game start because Proton can overwrite nvapi64.dll during prefix setup.
    Here we verify that the immutable shim payload is shipped and that the
    generated host wrapper points the launch at that full launcher path.
    Steam launch options and Lutris prefix_commands both exec that same
    wrapper, so either launcher being present is reason to install it.

    Hosts without any launcher are skipped: no wrapper, manifest, or shim
    files are written, and nothing here may keep the rest of the app
    (Auto-UV, profiles) from working. Managed files that already exist (an
    earlier version, or a manual penguin-burner-install-wrappers run) keep
    being repaired even without a launcher, so a flatpak update never strands
    stale generated files.
    """
    if not running_in_flatpak():
        return None
    if (
        not _host_has_steam()
        and not _host_has_lutris()
        and not _managed_integration_present()
    ):
        return None
    ensure_flatpak_wrappers()
    wrapper = _default_bin_dir() / "PENGUIN_BURNER"
    if not wrapper.is_file() or not os.access(wrapper, os.X_OK):
        raise RuntimeError(f"mandatory Steam wrapper is unavailable: {wrapper}")
    if not _is_managed_wrapper(wrapper) and not _is_native_steam_wrapper(wrapper):
        raise RuntimeError(
            f"existing Steam wrapper is not owned by PenguinBurner: {wrapper}"
        )

    manifest = install_vulkan_layer_manifest()
    if manifest is None:
        raise RuntimeError("packaged Vulkan latency layer is missing")

    _require_packaged_nvapi_shim()
    return wrapper


def _host_has_steam() -> bool:
    from integrations.steam.users import default_steam_root

    return default_steam_root() is not None


def _host_has_lutris() -> bool:
    # The library database, not the binary: the sandbox cannot see the host
    # PATH, but the host home is mounted, and a machine with a Lutris library
    # is exactly one whose games may carry our wrapper in a prefix_command.
    from integrations.lutris.paths import lutris_installed

    return lutris_installed()


def _managed_integration_present() -> bool:
    bin_dir = _default_bin_dir()
    if any(
        _is_managed_wrapper(bin_dir / name)
        for name in WRAPPERS + LEGACY_WRAPPERS
    ):
        return True
    return _is_managed_vulkan_manifest(_default_vulkan_manifest_path())


def _require_packaged_nvapi_shim() -> Path:
    from overlay.shim_deploy import nvapi_shim_artifact

    shim = nvapi_shim_artifact()
    if shim is None:
        raise RuntimeError("packaged NVAPI shim is missing")
    try:
        if shim.read_bytes()[:2] != b"MZ":
            raise RuntimeError(f"packaged NVAPI shim is invalid: {shim}")
    except OSError as exc:
        raise RuntimeError(f"packaged NVAPI shim is unreadable: {exc}") from exc
    return shim


def _is_managed_vulkan_manifest(path: Path) -> bool:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    return (
        "VK_LAYER_PENGUINBURNER_latency" in text
        and NATIVE_LAYER_LIBRARY in text
        and VULKAN_LAYER_ENABLE_ENV in text
    )


def uninstall_vulkan_layer_manifest(*, home: Path | str | None = None) -> Path | None:
    target = _default_vulkan_manifest_path(home)
    if not target.exists() or not _is_managed_vulkan_manifest(target):
        return None
    target.unlink()
    return target


def _wrapper_text(command_name: str) -> str:
    if command_name == "PENGUIN_BURNER":
        return _steam_wrapper_text()
    return _flatpak_command_wrapper_text(command_name)


def _flatpak_command_wrapper_text(command_name: str) -> str:
    return (
        "#!/usr/bin/env sh\n"
        f"# {MARKER}\n"
        "if [ \"$(id -u)\" = 0 ]; then\n"
        "    desktop_user=\"${PENGUIN_BURNER_Q2RTX_USER:-${SUDO_USER:-}}\"\n"
        "    if [ -n \"$desktop_user\" ] && command -v getent >/dev/null 2>&1; then\n"
        "        desktop_home=\"$(getent passwd \"$desktop_user\" | cut -d: -f6)\"\n"
        "        if [ -n \"$desktop_home\" ]; then\n"
        "            export HOME=\"$desktop_home\"\n"
        "            export XDG_DATA_HOME=\"${XDG_DATA_HOME:-$desktop_home/.local/share}\"\n"
        "        fi\n"
        "    fi\n"
        "fi\n"
        f'exec /usr/bin/flatpak run --user --command={command_name} {APP_ID} "$@"\n'
    )


def _steam_wrapper_text() -> str:
    return (
        "#!/usr/bin/env sh\n"
        f"# {MARKER}\n"
        "set -eu\n"
        "if [ \"$#\" -eq 0 ]; then\n"
        "    echo \"Usage: $0 %command%\" >&2\n"
        "    exit 2\n"
        "fi\n"
        "run_flatpak_clean() (\n"
        "    unset LD_PRELOAD LD_LIBRARY_PATH LD_AUDIT\n"
        "    exec /usr/bin/flatpak \"$@\"\n"
        ")\n"
        "app_id=\"${PENGUIN_BURNER_FLATPAK_APP_ID:-io.github.jpietek.PenguinBurner}\"\n"
        "app_files=\"${PENGUIN_BURNER_FLATPAK_APP_PATH:-}\"\n"
        "if [ -z \"$app_files\" ]; then\n"
        "    app_location=\"$(run_flatpak_clean info --user --show-location \"$app_id\" 2>/dev/null || run_flatpak_clean info --show-location \"$app_id\" 2>/dev/null || true)\"\n"
        "    active_location=\"${app_location%/*}/active\"\n"
        "    if [ -d \"$active_location/files\" ]; then\n"
        "        app_location=\"$active_location\"\n"
        "    fi\n"
        "    [ -n \"$app_location\" ] && app_files=\"$app_location/files\"\n"
        "fi\n"
        "site_packages=\"\"\n"
        "for candidate in \"$app_files\"/lib/python*/site-packages; do\n"
        "    if [ -d \"$candidate\" ]; then\n"
        "        site_packages=\"$candidate\"\n"
        "    fi\n"
        "done\n"
        "if [ -z \"$site_packages\" ]; then\n"
        "    echo \"PenguinBurner Flatpak payload is incomplete: Python package not found\" >&2\n"
        "    exit 127\n"
        "fi\n"
        "host_python=\"${PENGUIN_BURNER_HOST_PYTHON:-/usr/bin/python3}\"\n"
        "if [ ! -x \"$host_python\" ]; then\n"
        "    echo \"PenguinBurner requires host Python at $host_python\" >&2\n"
        "    exit 127\n"
        "fi\n"
        "export PENGUIN_BURNER_NATIVE_LAYER_DIR=\"$site_packages/overlay/native_layer\"\n"
        "export PENGUIN_BURNER_NVAPI_SHIM_DIR=\"$site_packages/overlay/nvapi_shim\"\n"
        "export PENGUIN_BURNER_SESSION_HELPER_PYTHONPATH=\"$site_packages\"\n"
        "exec \"$host_python\" -c 'import sys; sys.path.insert(0, sys.argv.pop(1)); from overlay.launcher import main; raise SystemExit(main())' \"$site_packages\" \"$@\"\n"
    )


def install_wrappers(bin_dir: Path, *, force: bool = False) -> list[Path]:
    bin_dir = bin_dir.expanduser()
    bin_dir.mkdir(parents=True, exist_ok=True)
    installed = []
    for command_name in WRAPPERS:
        target = bin_dir / command_name
        if target.exists() and not force and not _is_managed_wrapper(target):
            raise RuntimeError(
                f"refusing to overwrite existing command: {target} "
                "(rerun with --force)"
            )
        _write_wrapper_atomic(target, _wrapper_text(command_name))
        installed.append(target)
    _remove_legacy_wrappers(bin_dir)
    return installed


def uninstall_wrappers(bin_dir: Path) -> tuple[list[Path], list[Path]]:
    removed = []
    skipped = []
    for command_name in WRAPPERS + LEGACY_WRAPPERS:
        target = bin_dir.expanduser() / command_name
        if not target.exists():
            continue
        if not _is_managed_wrapper(target):
            skipped.append(target)
            continue
        target.unlink()
        removed.append(target)
    return removed, skipped


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        if args.uninstall:
            removed, skipped = uninstall_wrappers(args.bin_dir)
            removed_manifest = uninstall_vulkan_layer_manifest()
            from overlay.shim_deploy import restore_all_nvapi_shims

            restored_prefixes = restore_all_nvapi_shims()
            for path in removed:
                print(f"removed {path}")
            if removed_manifest is not None:
                print(f"removed {removed_manifest}")
            for path in restored_prefixes:
                print(f"restored NVAPI in {path}")
            for path in skipped:
                print(f"skipped non-managed command: {path}", file=sys.stderr)
            return 0

        installed = install_wrappers(args.bin_dir, force=args.force)
        manifest = install_vulkan_layer_manifest()
        if manifest is None:
            raise RuntimeError("packaged Vulkan latency layer is missing")
        _require_packaged_nvapi_shim()
        for path in installed:
            print(f"installed {path}")
        print(f"installed {manifest}")
        if "FLATPAK_ID" not in os.environ:
            path_entries = os.environ.get("PATH", "").split(os.pathsep)
            if str(args.bin_dir.expanduser()) not in path_entries:
                print(
                    f"warning: {args.bin_dir.expanduser()} is not on PATH; "
                    "add it to use pburn directly",
                    file=sys.stderr,
                )
        return 0
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
